os: linux
language: ruby
dist: bionic

env:
  global:
    - secure: UXeUpG/kS/8PfTsl+BUR9XUxnZBKfLkgjZ14QFDG+85/NgDeZYAUpLkhdKOtPdD4cko89BVGAA9c8uuxUeLVRIq0cFlKKyiRBdfRMGSo/GpY9xUwTzawx5r++fUSL9uCqtAVvKmNQUQnzGSOlzTw4btKpKnTFUD3Jq4Xch3fuiQXnb1Eqfh42VFDotnpcY3YgDSFKivE7VKQlpfxZ0VND8si7VqO4ML9D2eZ5lESsxRY8tcTjpppdsH/t5Mown7Z0nkanK9/8fj15nB76ayeTDo0TNvkcu+t/f93KuIXL2v/IRoUqHGlqQDw7lYTXikghu4hzZK0adkhGc7mZzDxhB/d+helQyDa2NliHhZk63Bg4S8nQs/PcynmnJrlx9wTV1IawLGVYEXBgzsNpIrR4uC1REo+xV8+/t9D9w6BmcsyH35iWwgwle82BhLxn6lmIAdAur/b2x4mo2NXFqq0MzeoFgymrZ6kAKYJMEbbpJkaryRaXsx8inQEgtlLSnL1gcr4mt8GQLSiVPtjDfGN3io4ge7NVC1xSVY1a3pNnWyvUZyXNZn9cc5/yHEot65elq1qg9bWLWtZnC8b51WimbiohnveUMhBjrdC4yCVJOjKLf2vx/lFCG8+ObmcI0vx2XtwESZ3cf3MqQD7dlnnDQzVuIYpRkup38AVhg86XzY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/nginx-ultimate-bad-bot-blocker
    - GIT_BRANCH: master

jobs:
  fast_finish: true

addons:
    apt:
        packages:
        - mailutils

before_install:
  - export TZ=Africa/Johannesburg

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --assume-yes nginx-extras
  - sudo apt-get -y install dos2unix

script:
  # GENERATE BLOCKER FILES
  - bash .dev-tools/generate-files.sh
  # THE NEWLY GENERATED BLOCKER FILES
  - bash .dev-tools/install-nginx-1.sh
  - bash .dev-tools/test-blocker-false-positives.sh
  - bash .dev-tools/test-blocker-quick.sh
  - bash .dev-tools/test-blocker-badwords.sh
  - bash .dev-tools/test-blocker-whitelist-domains.sh
  - bash .dev-tools/test-blocker-whitelist-ips.sh
  - bash .dev-tools/test-blocker-rate-limiting.sh
  - bash .dev-tools/test-blocker-whitelist.sh
  # TEST install-ngxblocker update-ngxblocker and setup-ngxblocker
  - bash .dev-tools/install-nginx-2.sh
  - bash .dev-tools/test-nginx-2.sh
  - bash .dev-tools/install-nginx-3.sh
  - bash .dev-tools/test-nginx-3.sh
  - bash .dev-tools/test-setupngxblocker.sh
  # TEST ANY NEW CHANGES TO THE BLOCKER
  - bash .dev-tools/install-nginx-1.sh
  - bash .dev-tools/beta-install-nginx-testing-of-changes.sh
  - bash .dev-tools/beta-test-blocker-false-positives.sh
  - bash .dev-tools/beta-test-blocker.sh
  - bash .dev-tools/beta-test-blocker-badwords.sh
  - bash .dev-tools/beta-test-blocker-whitelist-domains.sh
  - bash .dev-tools/beta-test-blocker-whitelist-ips.sh
  - bash .dev-tools/beta-test-blocker-rate-limiting.sh
  - bash .dev-tools/beta-test-blocker-whitelist.sh
  # TEST NGINX MAINLINE
  - bash .dev-tools/install-nginx-mainline-ppa.sh
  - bash .dev-tools/test-nginx-mainline-ppa.sh
  # IF ALL TESTS PASSED - COMMIT AND DEPLOY BUILD
  - bash .dev-tools/modify-files-and-commit.sh

before_deploy:
  - bash .dev-tools/deploy-package.sh

deploy:
  provider: releases
  token: ${GH_TOKEN}
  file: "FILE TO UPLOAD"
  cleanup: true
  on:
    repo: mitchellkrogza/nginx-ultimate-bad-bot-blocker
    tags: false
    branches:
      only:
       - "master"
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
notifications:
  on_success: change
  on_failure: always
